name: Docker Build & Push
on:
  push: {}

jobs:
  test_run:
    name: Test Run
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: docker-compose build

      - name: Start containers
        run: |
          docker-compose up --detach

      - name: Ensure containers are still running
        run: |
          sleep 30
          docker-compose logs --tail 50
          docker-compose exec -T minecraft echo hi there

  docker:
    name: Docker Build
    needs: [test_run]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
